name: Mac

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.arch == 'arm64' && 'macos-14' || 'macOS-13' }}
    timeout-minutes: 60
    strategy: 
      matrix:
        arch: [arm64, x86-64]
        options: [--with-sb-thread, --with-mark-region-gc]
        include:
          - { os: x86-64, options: --without-sb-thread }
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: instal host sbcl
      run: brew install sbcl
    - name: build
      env:  
        SBCL_MAKE_TARGET_2_OPTIONS: --disable-ldb --disable-debugger
        CPATH: /opt/homebrew/include
        LIBRARY_PATH: /opt/homebrew/lib
      run: ./make.sh ${{ matrix.options }} --with-sb-core-compression --xc-host='sbcl --lose-on-corruption --disable-ldb --disable-debugger'
    - name: make binary
      run: |
        name=sbcl-`cat version.lisp-expr | ./run-sbcl.sh --noinform --noprint --eval '(write-line (read))'`-darwin-${{ matrix.arch }}
        mkdir sbcl-mac-binary-${{ matrix.arch }}${{ matrix.options }}
        cd ..
        mv sbcl $name
        ./$name/binary-distribution.sh $name
        bzip2 $name-binary.tar
        mv $name sbcl
        mv $name-binary.tar.bz2 sbcl/sbcl-mac-binary-${{ matrix.arch }}${{ matrix.options }}
    - name: save binary
      uses: actions/upload-artifact@v1
      with:
        name: sbcl-mac-binary-${{ matrix.arch }}${{ matrix.options }}
        path: sbcl-mac-binary-${{ matrix.arch }}${{ matrix.options }}
    - name: test
      run: cd tests; ./run-tests.sh --slow
    - name: ansi-test
      run: cd tests; ./ansi-tests.sh
